# Copyright The Linux Foundation and each contributor to LFX.
# SPDX-License-Identifier: MIT
---
name: Publish Container Branch

"on":
  pull_request:
    branches:
      - main

permissions:
  contents: read

jobs:
  publish:
    name: Publish Container
    if: false
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0  # v7.0.0
      - uses: actions/setup-go@d35c59abb061a4a6fb18e82ac0862c26744d6ab5  # v5
        with:
          go-version-file: go.mod
      - uses: ko-build/setup-ko@d006021bd0c28d1ce33a07e7943d48b079944c8d  # v0.9
        with:
          version: v0.18.0
      - name: Prepare container tag
        id: container_tag
        env:
          HEAD_REF: ""
        run: |
          container_tag=$(echo "$HEAD_REF" | sed 's/[^_0-9a-zA-Z]/-/g' | cut -c -127)
          echo tag="$container_tag" >> "$GITHUB_OUTPUT"
      - name: Build subscription-api for PR
        env:
          VERSION: 
        run: |
          BUILD_TIME=$(date -u '+%Y-%m-%d_%H:%M:%S')
          GIT_COMMIT=""
          GIT_COMMIT="${GIT_COMMIT:0:7}"
          export BUILD_TIME
          export GIT_COMMIT
          ko build github.com/linuxfoundation/lfx-v2-subscription-service/cmd/subscription-api \
            -B \
            --platform linux/amd64,linux/arm64 \
            -t  \
            -t  \
            --sbom spdx
